global:
  scrape_interval: 5s # How frequently to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Scrape Prometheus itself

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Assuming node-exporter service in doc>

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
