services:
  # Bazarr - Subtitle Management
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: "unless-stopped"
    ports:
      - "6767:6767"
    volumes:
      - $DATADIR/Media:/data/media
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID