services:
  # Grafana - Graphical data visualization for InfluxDB data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - default
    ports:
      - "3000:3000"
    user: "$PUID:$PGID"
    volumes:
      - $DOCKERDIR/appdata/grafana:/var/lib/grafana