services:
  # Grafana - Graphical data visualization for InfluxDB data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "$PUID:$PGID"