services:
  # Client for Notifiarr.com
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    restart: "unless-stopped"
    ports:
      - "5454:5454"
    volumes:
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id