services:
  # Client for Notifiarr.com
  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    restart: "unless-stopped"
    ports:
      - "5454:5454"
    volumes:
      - $DOCKERDIR/appdata/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      DN_API_KEY: $NOTIFIARR_API_KEY
      DN_AUTO_UPDATE: off