services:
  # qBittorrent - Torrent downloader
  # Needs trailing / if using PathPrefixStrip
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8081:8080" # Explosed via gluetun. 8081 because crowdsec is using port 8080
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - $DATADIR/Media/Downloads:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID