services:
  # Radarr - Movie management
  # Set url_base in radarr settings if using PathPrefix
  radarr:
    image: lscr.io/linuxserver/radarr:latest # latest was causing "Error parsing column 45"
    container_name: radarr
    restart: "unless-stopped"
    ports:
      - "7878:7878"
    volumes:
      - $DATADIR/Media/Movies:/data/movies
      - $DATADIR/Media/Downloads:/data/downloads 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID