services:
  # Tautulli - Plex statistics and monitoring
  # Set HTTP Root in Tautulli settings if using PathPrefix
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: "unless-stopped"
    ports:
      - "8181:8181"
    volumes:
      - $DOCKERDIR/logs/plex:/logs:ro # For ta>
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
